# Generated by Django 4.2.11 on 2025-11-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth',
            field=models.CharField(max_length=10),
        ),
    ]
