# sao_gabriel/settings.py (NO TOPO DO ARQUIVO)

import pymysql
pymysql.install_as_MySQLdb()

"""
Django settings for sao_gabriel project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# O resto do seu arquivo settings.py começa aqui...
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6x)t22)01f#v8m^la2(l58xtx_af(dh^%%nok@#%!k!wcyad$%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'social_django',
     
    'users',
    'product',
    'pagamento',
    'app_admin',
    'store',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'pagamento': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Define o nível para exibir todos os logs (incluindo ERROR)
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # Manter logs padrão do Django
            'propagate': True,
        },
    },
}
#api logingoogle
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2', 
    'django.contrib.auth.backends.ModelBackend',  
)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/index'  
LOGOUT_REDIRECT_URL = '/login'  

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sao_gabriel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sao_gabriel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#minhaconfig
# sao_gabriel/settings.py
# sao_gabriel/settings.py (Na seção DATABASES)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'bd_coffee', 
        'USER': 'root', 
        'PASSWORD': '', 
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# sao_gabriel/settings.py (Adicione no final do arquivo)


# -----------------------------------------------------




# URL para redirecionar após o login bem-sucedido (sem parâmetros 'next')
LOGIN_REDIRECT_URL = '/index' # Redireciona para a página inicial (listar_produtos)
# ...

# URL onde o Django deve buscar a página de login.
# Já está implícito na sua view, mas é bom ter no settings também.
LOGIN_URL = '/contas/login/' # Ou 'contas/login/' se você seguiu o passo 1

# --- Configurações do Mercado Pago (Sandbox/Teste) ---
MP_ACCESS_TOKEN = 'APP_USR-2201546978636815-111017-c7629d7e22017f3b3ad4ca670d35e378-2979950899'